// <auto-generated />
using System;
using HospitalCMS_API.Data.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalCMS_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230720040318_PopulatePatientsTable")]
    partial class PopulatePatientsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalCMS_API.Models.DoctorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Awards")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegreeInitials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuickDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalCMS_API.Models.MedicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intake")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Prescribed")
                        .HasColumnType("datetime2");

                    b.Property<int>("RefillsNumber")
                        .HasColumnType("int");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("HospitalCMS_API.Models.PatientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalSex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 55,
                            Ethnicity = "Caribbean",
                            FirstName = "Trinidad",
                            Height = 5.1m,
                            Language = "English",
                            LastName = "Franklin",
                            LegalSex = "Female",
                            MaritalStatus = "Married",
                            Race = "African American",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 975, DateTimeKind.Local).AddTicks(6184),
                            Weight = 210.5m
                        },
                        new
                        {
                            Id = 2,
                            Age = 23,
                            Ethnicity = "American",
                            FirstName = "Ashley",
                            Height = 5.5m,
                            Language = "English",
                            LastName = "Castaneda",
                            LegalSex = "Female",
                            MaritalStatus = "Single",
                            Race = "Hispanic",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 986, DateTimeKind.Local).AddTicks(5460),
                            Weight = 131.8m
                        },
                        new
                        {
                            Id = 3,
                            Age = 32,
                            Ethnicity = "Irish",
                            FirstName = "Josh",
                            Height = 5.7m,
                            Language = "English",
                            LastName = "McGlade",
                            LegalSex = "Male",
                            MaritalStatus = "Married",
                            Race = "European American",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 986, DateTimeKind.Local).AddTicks(5476),
                            Weight = 248.8m
                        },
                        new
                        {
                            Id = 4,
                            Age = 68,
                            Ethnicity = "American",
                            FirstName = "Shanon",
                            Height = 5.6m,
                            Language = "English",
                            LastName = "Anderson",
                            LegalSex = "Female",
                            MaritalStatus = "Divorced",
                            Race = "White American",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 986, DateTimeKind.Local).AddTicks(5480),
                            Weight = 109.3m
                        },
                        new
                        {
                            Id = 5,
                            Age = 51,
                            Ethnicity = "American",
                            FirstName = "Wilson",
                            Height = 5.11m,
                            Language = "English",
                            LastName = "Li",
                            LegalSex = "Male",
                            MaritalStatus = "Married",
                            Race = "Asian American",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 986, DateTimeKind.Local).AddTicks(5483),
                            Weight = 139.2m
                        },
                        new
                        {
                            Id = 6,
                            Age = 39,
                            Ethnicity = "South American",
                            FirstName = "Miguel",
                            Height = 5.9m,
                            Language = "Spanish",
                            LastName = "Pena",
                            LegalSex = "Male",
                            MaritalStatus = "Divorced",
                            Race = "Hispanic",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 986, DateTimeKind.Local).AddTicks(5491),
                            Weight = 197.3m
                        },
                        new
                        {
                            Id = 7,
                            Age = 47,
                            Ethnicity = "American",
                            FirstName = "Robert",
                            Height = 5.8m,
                            Language = "English",
                            LastName = "Bush",
                            LegalSex = "Male",
                            MaritalStatus = "Divorced",
                            Race = "European American",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 986, DateTimeKind.Local).AddTicks(5494),
                            Weight = 233.2m
                        },
                        new
                        {
                            Id = 8,
                            Age = 39,
                            Ethnicity = "Norwegian",
                            FirstName = "Michelle",
                            Height = 5.6m,
                            Language = "English",
                            LastName = "Hagen",
                            LegalSex = "Female",
                            MaritalStatus = "Single",
                            Race = "European American",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 986, DateTimeKind.Local).AddTicks(5497),
                            Weight = 210.3m
                        },
                        new
                        {
                            Id = 9,
                            Age = 55,
                            Ethnicity = "Scottish",
                            FirstName = "Norris",
                            Height = 6.0m,
                            Language = "English",
                            LastName = "McKenney",
                            LegalSex = "Male",
                            MaritalStatus = "Divorced",
                            Race = "European American",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 986, DateTimeKind.Local).AddTicks(5500),
                            Weight = 173.8m
                        },
                        new
                        {
                            Id = 10,
                            Age = 62,
                            Ethnicity = "American",
                            FirstName = "Krista",
                            Height = 5.3m,
                            Language = "English",
                            LastName = "Thomas",
                            LegalSex = "Female",
                            MaritalStatus = "Married",
                            Race = "Native American",
                            RegisterDate = new DateTime(2023, 7, 19, 23, 3, 17, 986, DateTimeKind.Local).AddTicks(5504),
                            Weight = 190.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
